### 教师
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "2001",
  "password": "2001"
}

> {% client.global.set("token", response.headers.valueOf("token")); %}
###
GET http://localhost:8080/api/teacher/process/processes
token: {{token}}

###
POST http://localhost:8080/api/teacher/process/processscores
token: {{token}}
Content-Type: application/json

{
  "processId": "1070382937616666624",
  "studentId": "1070387139730460672",
  "detail": "{\n                \"scores\": 80, \n                \"details\": [{\"number\": 0, \"score\": 40}, {\"number\": 1, \"score\": 40}]\n                }"
}
### 指定过程，评审
GET http://localhost:8080/api/teacher/process/processes/1070382937616666624
token: {{token}}

### 指定过程，指导教师
GET http://localhost:8080/api/teacher/process/processes/1070552139027697664
token: {{token}}